### ISSUE TITLE
Scripts for collapsing/binarizing ptb trees

### ISSUE THREAD

**Issue by bo-son** [NYU-MLL/spinn#99]
Hi, could you make public the scripts for unary-collapsing and binarizing the original PTB trees? I want to make sure that I use the same trees as you did. Thanks a lot!

**Comment by sleepinyourhat** [comment]
I don't really know Java, but I cobbled this script together a while back, and it contains the core operations that were used for both SNLI and MultiNLI. You'll probably have to re-do the IO to fit whatever data format you're working with, but otherwise, you should just be able to run this in a directory that contains the 04/20/15 release of Stanford CoreNLP.

[ParseImageFlickrOneCol.java.zip](https://github.com/nyu-mll/spinn/files/4294864/ParseImageFlickrOneCol.java.zip)

**Comment by bo-son** [comment]
Thank you very much! Helped me a lot.
